use_frameworks!

target 'WTLStickerPanel_Example' do
  pod 'WTLStickerPanel', :path => '../'

  target 'WTLStickerPanel_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
